AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  farkle-app

  SAM for farkle-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
# THE ORDER of GET, HEAD, OPTIONS, POST seems to matter here. ??!
Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'GET,HEAD,OPTIONS,POST'"
      AllowHeaders: "'Content-Type, X-Forwarded-For'"
      AllowOrigin: "'*'"


Resources:
  FarkleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: farkle/
      Handler: app.shared_handler
      Runtime: python3.8
      Policies: AmazonDynamoDBFullAccess
      Events:
        Roll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /farkle/{command}
            Method: post


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FarkleApi:
    Description: "base url for application"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/farkle"
  FarkleFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt FarkleFunction.Arn
  FarkleIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt FarkleFunctionRole.Arn
